### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by freeznet** [lfq7413/tomato#26]
https://github.com/lfq7413/tomato/blob/master/storage/postgres/PostgresStorageAdapter.go#L1316
```
goroutine 40 [running]:
runtime.throw(0x17ce5fd, 0x26)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:596 +0x95 fp=0xc420422058 sp=0xc420422038
runtime.mapiternext(0xc420422700)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/hashmap.go:737 +0x7ee fp=0xc420422108 sp=0xc420422058
github.com/lfq7413/tomato/storage/postgres.postgresObjectToParseObject(0xc420661bc0, 0xc420256090, 0xc420422950, 0xc420697758, 0xc420661bc0)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/storage/postgres/PostgresStorageAdapter.go:1316 +0x109 fp=0xc420422770 sp=0xc420422108
github.com/lfq7413/tomato/storage/postgres.(*PostgresAdapter).Find(0xc4201f0240, 0xc42018c131, 0x6, 0xc420256060, 0xc42020fbc0, 0xc42020fad0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/storage/postgres/PostgresStorageAdapter.go:849 +0xd89 fp=0xc420422af0 sp=0xc420422770
github.com/lfq7413/tomato/orm.(*DBController).Find(0x1b8cd18, 0xc42018c131, 0x6, 0xc42020fbc0, 0xc42020fad0, 0xc42020eae0, 0xc42045f3e0, 0x8, 0xc4203c3188, 0x10100c42020eab0)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/orm/controller.go:194 +0x908 fp=0xc420422ce8 sp=0xc420422af0
github.com/lfq7413/tomato/rest.(*Query).runFind(0xc42013abe0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/rest/query.go:594 +0x503 fp=0xc420422f40 sp=0xc420422ce8
github.com/lfq7413/tomato/rest.(*Query).Execute(0xc42013abe0, 0x0, 0x0, 0x0, 0xc42020f050, 0xc42020eea0, 0xc42013abe0)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/rest/query.go:190 +0x6e fp=0xc420422f80 sp=0xc420422f40
github.com/lfq7413/tomato/rest.Find(0xc4201c4120, 0xc42018c131, 0x6, 0xc42020eab0, 0xc42020f050, 0xc42020eea0, 0xc42018c450, 0x2, 0xc42045f5a0)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/rest/rest.go:40 +0x168 fp=0xc420423008 sp=0xc420422f80
github.com/lfq7413/tomato/controllers.(*ClassesController).HandleFind(0xc4202e2000)
	/Users/rui/go_playground/src/github.com/lfq7413/tomato/controllers/classes.go:243 +0x70b fp=0xc420423390 sp=0xc420423008
runtime.call32(0xc420392870, 0xc420278058, 0xc420278060, 0x800000008)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:514 +0x48 fp=0xc4204233c0 sp=0xc420423390
reflect.Value.call(0x17a4c20, 0xc4202e2000, 0x7a13, 0x17affa3, 0x4, 0x1b8cd18, 0x0, 0x0, 0xc420278048, 0x13, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f fp=0xc420423708 sp=0xc4204233c0
reflect.Value.Call(0x17a4c20, 0xc4202e2000, 0x7a13, 0x1b8cd18, 0x0, 0x0, 0x1b8cd18, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4 fp=0xc420423770 sp=0xc420423708
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc4200a53f0, 0x1b38160, 0xc420314000, 0xc42024c500)
	/Users/rui/go_playground/src/github.com/astaxie/beego/router.go:815 +0x2031 fp=0xc420423d10 sp=0xc420423770
net/http.serverHandler.ServeHTTP(0xc4200a54a0, 0x1b38160, 0xc420314000, 0xc42024c500)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92 fp=0xc420423d58 sp=0xc420423d10
net/http.(*conn).serve(0xc42013a640, 0x1b38ba0, 0xc42049dec0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612 fp=0xc420423fc8 sp=0xc420423d58
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420423fd0 sp=0xc420423fc8
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
```

**Comment by lfq7413** [comment]
tomato 默认使用了内存缓存： inMemoryCacheAdapter ，直接把对象加入到了缓存中管理，所以每次取到的都是同一对象，如果保存的是 map ，当多线程同时操作时就会出错。
每个类的 schema 也是放入缓存管理的，所以对同一个类同时操作时，也会有几率出问题。
